# Base image
FROM python:3.10

# Upgrade pip
RUN pip install --upgrade pip

# Install each dependency
RUN pip install openai==1.6.0
RUN pip install opencv-python-headless==4.8.1.78
RUN pip install psycopg2-binary==2.9.9
RUN pip install pydantic==2.5.2
RUN pip install python-dotenv==1.0.0
RUN pip install SQLAlchemy==2.0.23
RUN pip install streamlit==1.29.0
RUN pip install streamlit-lottie==0.0.5